services:
  app:
    image: antonioanerao/laravel
    container_name: mentoship-app
    volumes:
      - ./laravel/:/laravel
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mentorship.rule=Host(`mentorship.sigep.docker.localhost`)"
      - "traefik.http.routers.mentorship.entrypoints=web"
networks:
  proxy:
    external: true
